In [83]:
# Learning how to use arrays and masking
# new functions learned : np.ma.masked_array(arr,[masking condition])
# also learned np.isnan, np.greater, np.equal

In [84]:
import numpy as np
import matplotlib

In [85]:
a = [1,2,3]
b = a*2
print(b)

[1, 2, 3, 1, 2, 3]


In [86]:
a = np.array(b)

In [87]:
a.dtype

dtype('int64')

In [88]:
a

array([1, 2, 3, 1, 2, 3])

In [89]:
b

[1, 2, 3, 1, 2, 3]

In [90]:
arr = np.array([[1,2,3],[4,5,6],[7,np.nan,9]])

In [91]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.]])

In [92]:
arr = np.ma.masked_array(arr, np.isnan(arr))

In [93]:
arr

masked_array(
  data=[[1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0],
        [7.0, --, 9.0]],
  mask=[[False, False, False],
        [False, False, False],
        [False,  True, False]],
  fill_value=1e+20)

In [94]:
arr = np.ma.masked_array(arr, np.equal(arr,2))

In [95]:
arr

masked_array(
  data=[[1.0, --, 3.0],
        [4.0, 5.0, 6.0],
        [7.0, --, 9.0]],
  mask=[[False,  True, False],
        [False, False, False],
        [False,  True, False]],
  fill_value=1e+20)

In [96]:
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [97]:
np.greater(arr2,45)

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [98]:
arr3 = np.ma.masked_array(arr2, np.greater(arr2,45.0))

In [99]:
arr3

masked_array(
  data=[[10, 20, 30],
        [40, --, --],
        [--, --, --]],
  mask=[[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]],
  fill_value=999999)